### ISSUE TITLE
Add a Fabric mods section

### ISSUE THREAD

**Issue by Shnupbups** [windy1/Pore#846]
**Is your feature request related to a problem? Please describe.**
Frankly, myself and a lot of modders are sick of CurseForge and would love an alternative, which Ore seems to provide. Despite being primarily built for Sponge plugins, it does have a section for Forge mods, but none for mods built for other modloaders such as Fabric.

**Describe the solution you'd like**
I'd like for there to be a section on Ore, much like the existing 'Forge Mods' section, named 'Fabric Mods', where developers can post Minecraft mods intended for use with the Fabric Mod Loader created by asiekierka. (Which can be found [here](https://fabricmc.net/))

**Describe alternatives you've considered (optional)**
Of course, we could always continue to use CurseForge, but its support for non-Forge modloaders is also rather lackluster. We could also post Fabric mods on Ore under the 'Forge Mods' section, but that seems more than a touch misleading.

EDIT: Fabric mods store their metadata in a file called `fabric.mod.json`, [here](https://fabricmc.net/wiki/documentation:fabric_mod_json) is the official documentation regarding said files.

**Comment by falseresync** [comment]
I support that :) Is would post my mod on Ore as soon as it would be possible

**Comment by liach** [comment]
Compared to forge coremods, etc. many fabric mods use mixins, which are easier to review and regulate.

Fabric mods are generally not too giant for revision as well.

**Comment by Katrix** [comment]
If we're going to support Fabric mods, we need a link to some schema or similar that describe the mod/plugin. Bukkit has plugin.yml, Forge/Sponge has mcmod.info, mixin adds stuff in META-INF/MANIFEST.MF, what does Fabric use?

**Comment by falseresync** [comment]
fabric.mod.json

https://fabricmc.net/wiki/documentation:fabric_mod_json

**Comment by liach** [comment]
Can close this one now as zidane has decided.

**Comment by ItsDoot** [comment]
Gathered from a private discussion earlier with other Ore staff, here's an explanation of why we won't be adding support for Fabric, for now.

Fabric is not in any way currently compatible with Sponge:
* There is no Sponge implementation for Fabric.
* Fabric cannot be run alongside Forge.

The web service we provide, called Ore, is for Sponge plugins, and mods for Sponge-compatible platforms. We support Forge mods on Ore because there is a Sponge implementation for Forge, meaning Forge is Sponge-compatible.

Though there isn't anything preventing someone from forking it (Ore is open source!) and running their own instance that supports Fabric mods, the service that we provide will not support Fabric mods until Fabric is Sponge-compatible.
